export const MISSION = [
    {
        contents: 'stamp_detail_001',
        code: "theme",
        stamp:'mission1',
        title: 'stamp_main_014',
        caption:"stamp_detail_003",
        img:"mo_space_theme",
        step: ['stamp_detail_005','stamp_detail_006'],
    },
    {
        contents: 'stamp_detail_007',
        code: "letter",
        stamp:'mission2',
        title: 'stamp_main_016',
        caption:"stamp_detail_009",
        img:"mo_space_mind",
        step: ['stamp_detail_011','stamp_detail_012'],
    },
    {
        contents: 'stamp_detail_013',
        code: "post",
        stamp:'mission3',
        title: 'stamp_main_018',
        caption:"stamp_detail_015",
        img:"mo_space_shopping",
        step: ['stamp_detail_017','stamp_detail_018'],
    },
    {
        contents: 'stamp_detail_019',
        code: "experience",
        stamp:'mission4',
        title: 'stamp_main_020',
        caption:"stamp_detail_021",
        img:"mo_space_exp",
        step: ['stamp_detail_023','stamp_detail_024'],
    },
    {
        contents: 'stamp_main_021',
        code: "survey",
        stamp:'mission5',
        title: 'stamp_main_022',
        caption:"",
        img:"",
        step: [],
    },
    {
        contents: 'stamp_main_023',
        code: "booths",
        stamp:'bonus',
        title: 'stamp_main_024',
        caption:"stamp_detail_027",
        img:"",
        step: ['stamp_detail_029','stamp_detail_027'],
    }
]
